"""Re-run required legacy checks without replacing the old demo's artifacts."""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output-dir', type=Path, required=True)
    args = parser.parse_args()
    output = args.output_dir.resolve()
    if output.exists(): parser.error('Preserve existing evidence directory')
    output.mkdir(parents=True)
    paths = sorted((ROOT/'src').rglob('*.py'))
    hashes = lambda: {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}
    report = {'complete': False, 'before': hashes(), 'checks': [],
              'scope': 'Fresh CLI/graph/drill/integration regression. verify_artifacts additionally reads retained historical deliverables; not proof of a newly submitted finals package.'}
    def save(): (output/'report.json').write_text(json.dumps(report, ensure_ascii=False, indent=2))
    save()
    commands = [
        ('cli', ['-m','delivery_guard.cli','run','--scenario','data/demo_factory.json','--incident','data/incidents/supplier_delay.json','--output',str(output/'demo_run.json')]),
        ('adversary', ['-m','delivery_guard.cli','evaluate','--scenario','data/demo_factory.json','--suite','data/adversarial_suite.json','--output',str(output/'adversarial_report.json')]),
        ('graph', ['-m','delivery_guard.cli','run-graph','--case-dir','data/cases/mendeley_drill','--replay','data/model_replays/mendeley_drill.json','--output',str(output/'public_data_graph_run.json')]),
        ('drill', ['-m','delivery_guard.cli','run-drill','--case-dir','data/cases/mendeley_drill','--replay','data/model_replays/mendeley_drill.json','--seed','20260810','--output',str(output/'chaos_drill_run.json')]),
        ('integration', ['scripts/run_integration_validation.py','--output',str(output/'integration_validation_report.json')]),
        ('retained_artifacts', ['scripts/verify_artifacts.py'])]
    for name, command in commands:
        result = subprocess.run([sys.executable,*command],cwd=ROOT,text=True,capture_output=True,timeout=180)
        report['checks'].append({'name':name,'command':command,'returncode':result.returncode,'stdout':result.stdout,'stderr':result.stderr})
        save()
        print(name,result.returncode,flush=True)
    # Use the actual rebuild entrypoint, redirecting only its declared output
    # directory, then compare generated bytes with retained source-case bytes.
    spec = importlib.util.spec_from_file_location('mendeley_rebuild',ROOT/'scripts/build_mendeley_case.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.CASE = output/'mendeley_rebuild'
    module.main()
    same = {name:(module.CASE/name).read_bytes()==(ROOT/'data/cases/mendeley_drill'/name).read_bytes()
            for name in ('scenario.json','lineage.json')}
    report['mendeley_byte_identical'] = same
    report.update(complete=True,unchanged=report['before']==hashes())
    report['passed'] = report['unchanged'] and all(same.values()) and all(c['returncode']==0 for c in report['checks'])
    save()
    raise SystemExit(0 if report['passed'] else 1)


if __name__ == '__main__': main()
